name: PTS Technical Issue Report
description: Log a new issue for the PTS Monitoring System.
title: "[ISSUE]: "
labels: ["Todo"]
body:
  - type: dropdown
    id: tse_name
    attributes:
      label: TSE Name
      options:
        - Abubakar Babangida
        - Amanwa Nicholas
        - Kamo Lanshima
        - Babatunde Olorunyomi
        - Rekus Friday
        - Abiem Chianen Samuel
        - Murtala Othman
        - Essien Jude Edem
        - Muazu Yahaya
        - Oluwaseyi Isaac
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Staff Email Address
      description: We will send status updates to this email.
      placeholder: name@company.com
    validations:
      required: true
  - type: input
    id: region
    attributes:
      label: Region
    validations:
      required: true
  - type: input
    id: Centre
    attributes:
      label: Center
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device/Asset Type
    validations:
      required: true
  - type: dropdown
    id: grouping
    attributes:
      label: Grouping of Issue
      options:
        - Hardware
        - Software
        - Network
        - Database
        - Office Infrastructure
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: Detailed Comments
      placeholder: Describe the issue in detail...
    validations:
      required: true
